version: '3.1'

services:

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: dev

  seq:
    image: datalust/seq
    container_name: seq
    restart: always
    ports:
      - 8081:80
    environment:
      ACCEPT_EULA: Y

  mongo:
      image: mongo
      container_name: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: dev

  mongo-express:
    image: mongo-express
    container_name: mongoxp
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
