version: '3.1'

services:

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: dev

  seq:
    image: datalust/seq
    container_name: seq
    restart: always
    ports:
      - 8081:80
    environment:
      ACCEPT_EULA: Y
